name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    # Login to Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build Backend Image
    - name: Build Backend Image
      run: |
        docker build -t deepak18052000/mean-backend:latest ./backend

    # Build Frontend Image
    - name: Build Frontend Image
      run: |
        docker build -t deepak18052000/mean-frontend:latest ./frontend

    # Push Images to Docker Hub
    - name: Push Images
      run: |
        docker push deepak18052000/mean-backend:latest
        docker push deepak18052000/mean-frontend:latest

    # SSH into EC2 and deploy
    - name: SSH & Deploy on EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd mean-app
          docker-compose pull
          docker-compose up -d
